Algoritmo "ExercicioC"
// Disciplina   : [Linguagem e Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   :Divisiveis por 4, até 200.
// Autor(a)    : Anthony Chukwudi Ndubisi
// Data atual  : 18/04/2024
Var
   count: inteiro

Inicio
   Repita
      count <- count + 1
      Se count % 4 = 0 entao
         Escreval("O número ", count, " é divisivel por 4")
      FimSe
   Até count > 200



Fimalgoritmo