Algoritmo "AreaDoTriangulo"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Área do Triângulo
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 14/04/2024
Var
// Seção de Declarações das variáveis 
base, altura:real

Inicio

Escreval("Area do Triângulo")
Escreva("Digite o valor da Base: ")
Leia(base)
Escreva("Digite o valor do Altura: ")
Leia(altura)
Escreval("A Área é: ", (base * altura) / 2)

Fimalgoritmo