Algoritmo "TrocarValores"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Trocar Valores
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 14/04/2024
Var
num1, num2, aux:inteiro

Inicio
Escreva("Digite o primeiro valor: ")
Leia(num1)
Escreva("Digite o segundo valor: ")
Leia(num2)
aux <- num1
num1 <- num2
num2 <- aux

Escreva("Os valores trocados são, respectivamente: ", num1, num2)

Fimalgoritmo