Algoritmo "ValorDeVeiculo"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Valor de Veículo
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 14/04/202
Var
custo, calc:real

Inicio
Escreva("Digite o valor de fabrica do veículo: ")
Leia(custo)

calc <- custo * (28/100) + custo * (45/100) + custo

Escreva("O valor final (impostos + valor do distribuidor) é: ", calc )

Fimalgoritmo