Algoritmo "MaiorQueDez"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Maior que 10
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 14/04/2024
Var
   num: inteiro

Inicio
   Escreva("Escreva um número: ")
   Leia(num)
   Se (num > 10) entao
      Escreva("É maior que 10!")
   Senao
      Escreva("Não é menor que 10!")
   Fimse


Fimalgoritmo