Algoritmo "MaiorValor"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Maior valor
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 14/04/2024
Var
   valor1, valor2:inteiro

Inicio
   Escreva("Digite um valor: ")
   Leia(valor1)
   Escreva("Digite outro valor: ")
   Leia(valor2)

   Se (valor1 > valor2) entao
      Escreva("O maior é: ", valor1)
   Senao
      Escreva("O maior é: ", valor2)
   Fimse

Fimalgoritmo