Algoritmo "ConverterFahrenheitemCelsius"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Converter Fahrenheit em Celsius
// Autor(a)    : Anthony Chukwudi Ndubisi
// Data atual  : 14/04/2024
Var

grausF, conversao: real

Inicio
Escreva("Digite a temperatura em Fahrenheit: ")
Leia(grausF)
conversao <- (grausF - 32) / 1.8
Escreva("A temperatura em Celsius é: ", conversao)


Fimalgoritmo