Algoritmo "ModuloDeUmNumero"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Módulo de um número
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 17/04/2024
Var
   num: inteiro

Inicio
   Escreva("Digite um valor: ")
   Leia(num)

   Se num < 0 entao
      Escreva("O módulo de",num," é: ", num * -1)
   Senao
      Escreva("O módulo de",num," é: ", num)
   FimSe



Fimalgoritmo