Algoritmo "ValorParOuImpar"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Verificar se um valor é par ou ímpar
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 17/04/2024
Var
   num: inteiro

Inicio
   Escreva("Digite um valor: ")
   Leia(num)

   Se num % 2 = 0 entao
      Escreva("O valor é par")
   Senao
      Escreva("O valor é impar")
   FimSe

Fimalgoritmo