Algoritmo "NumeroMenorQueTres"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Verificar se um número é menor que 3
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 17/04/2024
Var
   num: inteiro

Inicio
   Escreva("Digite um valor (menor que 3): ")
   Leia(num)

   Se num > 3 entao
      Escreva("Número maior que 3!")
   Senao
      Escreva("Número é: ", num)
   FimSe

Fimalgoritmo