Algoritmo "CelsiusParaFahrenheit"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Conversão de Celsius para Fahrenheit
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 17/04/2024
Var
grausC, conversao: real

Inicio
Escreva("Digite a temperatura em Celsius: ")
Leia(grausC)

conversao <- (9 * grausC + 160) / 5
Escreva("Em Fahrenheit fica: ", conversao)

Fimalgoritmo