Algoritmo "FahrenheitParaCelsius"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Conversão de Fahrenheit para Celsius
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 17/04/2024
Var
grausF, conversao: real

Inicio
Escreva("Digite a temperatura em Fahrenheit: ")
Leia(grausF)

conversao <- (grausF - 32) / 1.8
Escreva("Em Celsius fica: ", conversao)

Fimalgoritmo