Algoritmo "ConversaoDolaresParaReais"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Conversão de Dólares para Reais
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 17/04/2024

Var
cotacao, quantidade:real

Inicio
Escreva("Digite a cotação atual do Dolar (em R$): ")
Leia(cotacao)
Escreva("Digite a quantidade de dolares para conversão em reais: ")
Leia(quantidade)

Escreva("O valor convertido em R$: ", cotacao * quantidade)

Fimalgoritmo