Algoritmo "ConversaoReaisParaDolares"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Conversão de Reais para Dólares
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 17/04/2024
Var
cotacao, quantidade:real

Inicio
Escreva("Digite a cotação atual do Dolar (em R$): ")
Leia(cotacao)
Escreva("Digite a quantidade de reais para conversão em dolares: ")
Leia(quantidade)

Escreva("O valor convertido em US$: ", quantidade / cotacao)

Fimalgoritmo