Algoritmo "QuadradosDe15A200"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Quadrados de 15 a 200
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 17/04/2024
Var
   contadora: inteiro

Inicio
   contadora <- 15
   Repita
      Escreval("O número", contadora, " ao quadrado é: ", contadora ^ 2)
      contadora <- contadora + 1
   Ate contadora > 200


Fimalgoritmo