Algoritmo "DivisiveisPor4"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Divisíveis por 4
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 17/04/2024
Var
   count: inteiro

Inicio
   para count de 1 ate 200 passo 1 faca
      Se count % 4 = 0 entao
         Escreval("O número", count, " é divisivel por 4.")
      FimSe
   FimPara

Fimalgoritmo