Algoritmo "GrausCelsiusEmFahrenheit"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Graus Celsius em Fahrenheit
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 17/04/2024
Var
   gCelsius: inteiro
   gFahren: real

Inicio
   para gCelsius de 0 ate 100 passo 10 faca
      gFahren <- (9 * gCelsius + 160) / 5
      Escreval(gCelsius,"°C em Graus F°: ", gFahren)
   FimPara

Fimalgoritmo