Algoritmo "ImprimeTabuada"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Imprime uma tabuada
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 17/04/2024
Var
   num, mult: inteiro

Inicio
   Escreva("Digite um número: ")
   Leia(num)

   Escreval("")
   Escreva("A tabuada no número digitado é:")
   Enquanto mult <= 10 faca
      Escreval(num, "x", mult, " =", num * mult)
      mult <- mult + 1
   FimEnquanto
   


Fimalgoritmo