Algoritmo "SomaDosCemPrimeirosNumeros"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Soma dos cem primeiros números
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 17/04/2024
Var
   count, soma: inteiro

Inicio

   Enquanto count <= 100 faca
      soma <- soma + count
      count<- count + 1
   FimEnquanto
   
   Escreva("A soma de todos os cem primeiros números é: ", soma)

Fimalgoritmo