Algoritmo "ImparesDeZeroAVinte"
// Disciplina : [Linguagem e Lógica de Programação com JS]
// Professor : Jailson
// Descrição : Ímpares de 0 a 20
// Autor(a) : Anthony Chukwudi Ndubisi
// Data atual : 17/04/2024
Var
   count: inteiro

Inicio

   Enquanto count <= 20 faca
      Se count % 2 = 1 entao
         Escreval(count, " é Impar")
      FimSe
      count<- count + 1
   FimEnquanto

Fimalgoritmo